### ISSUE TITLE
netstat crash: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by ph1823** [danielkrainas/node-netstat#30]
Hi ! My node application crash with netstat. 

the error just occurred, i just reinstalled my server under centos 8, i hit something else, and my application crashed with the following error:

```
[30minecraft] PID is : 197037
/home/datahosting/new-manager/node_modules/node-netstat/lib/utils.js:68
    stream.on('data', function (data) {
           ^

TypeError: Cannot read property 'on' of undefined
    at exports.emitLines (/home/datahosting/new-manager/node_modules/node-netstat/lib/utils.js:68:12)
    at exports.async (/home/datahosting/new-manager/node_modules/node-netstat/lib/activators.js:48:5)
    at module.exports (/home/datahosting/new-manager/node_modules/node-netstat/lib/netstat.js:65:16)
    at Timeout._onTimeout (/home/datahosting/new-manager/server.js:53:3)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

My code code:
```
		netstat({
			filter: {
				pid: game.pid,
				state: 'LISTENING'
			}
		}, item => {
			done: error => {
				if (err) return;
					if (item.local.port != settings.params.port) {
						game.stdin.write(config.games[settings.gameType].stop + '\n');
						fs.appendFile('logs/logs-port-error.log', "\r\n[" + id + "] " + new Date() + ": Port used" + item.local.port + " allow port: " + settings.params.port, 'utf8', (err) => {
						});
					}
					return;
			}
		});
```
Thank for you help !

**Comment by ph1823** [comment]
Fixed. My centos 8 was problem with netstat command.
